'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Clfb3s4vauC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Button } from "./ui/button"
import { CopyIcon } from "lucide-react"

export function LandingPage() {
  return (
    <main className="flex flex-col items-center justify-center min-h-[100dvh] px-4 sm:px-6 lg:px-8 py-12 bg-background">
      <div className="max-w-2xl text-center space-y-4">
        <h1 className="text-4xl font-bold tracking-tighter text-foreground sm:text-5xl md:text-6xl">
          Blurhash generator
        </h1>
        <p className="text-muted-foreground text-lg md:text-xl">
          Generate a blurhash string from an image url in a post request and save it in your database
        </p>
        <div className="bg-muted rounded-lg p-6 text-left">
          <div className="flex flex-row items-center justify-between mb-4">
            <h2 className="text-xl font-semibold">Try it out:</h2>
            <div className="flex flex-row items-center">
              <Button
                variant="outline"
                size="sm"
                onClick={() => {
                  navigator.clipboard.writeText(
                    `
                      curl -X POST https://blurhash-generator.vercel.app/generate -H 'Content-Type: application/json' -d '{"url": "https://cdn.pixabay.com/photo/2015/03/17/02/01/cubes-677092_1280.png"}'
                    `
                  )
                }}
              >
                <CopyIcon className="w-5 h-5" />
              </Button>
            </div>
          </div>
          <pre className="bg-background rounded-md p-4 text-sm text-muted-foreground text-wrap">
            <code>
              curl -X POST https://blurhash-generator.vercel.app/generate \<br />
              -H &quot;Content-Type: application/json&quot; \<br />
              {`-d '{"url": "https://cdn.pixabay.com/photo/2015/03/17/02/01/cubes-677092_1280.png"}'`}
            </code>
          </pre>
        </div>
      </div>
    </main>
  )
}
